Add contributing guidelines
gitpod-samples/.github pull request #1
Opened 2022-11-30 07:04 UTC by Nancy-Chauhan

2022-11-30 10:28 UTC, pawlean requested changes
Apart from the comments above, it looks good to me. Thanks Nancy! 🙌

2022-11-30 10:28 UTC, pawlean commented on CONTRIBUTING.md
> +We ❤️ the people involved in Gitpod Samples, and we'd love to help you with contributing. Drop by the `#contributing` channel on the [Gitpod Discord server](https://www.gitpod.io/chat) and _ask for h
I'd reword this part:

We 🧡 all Gitpod Samples contributions! If you have any questions about contributing, drop by the `#contributing` channel on our community Discord server. See you there! 👋🏼

2022-11-30 10:28 UTC, pawlean commented on CONTRIBUTING.md
> +To submit a Pull request
Let's keep this consistent! 

> Pull request

pull request

2022-11-30 10:28 UTC, pawlean commented on CONTRIBUTING.md
> +Before reporting any issues or pull requests, please read through this document to ensure we have all the information to respond effectively to your contribution.
I would change this to simply: 

Before reporting any issues or raising pull requests, please read through this document 🙌

2022-12-07 08:44 UTC, MichaelAring approved these changes

2022-12-07 09:57 UTC, Siddhant-K-code approved these changes
LGTM ✨ 

Let's address the Open Comments before merge 🙏🏽

2022-12-07 10:29 UTC, merged